name: Main pipeline 
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      - name: 'Deploy'
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cdci-bry23" #Must be unique in Heroku
          heroku_email: "bryantt23@gmail.com"
          healthcheck: "https://cdci-bry23.herokuapp.com/health"
          checkstring: "ok"
